var express        = require('express');
var bodyParser     = require('body-parser');                    // pull information from HTML POST (express4)
var logger         = require('morgan');                         // log requests to the console (express4)
var app            = express();
var server 		   = require('http').Server(app);
var api            = require('./server/routes/api');


var rootFolder = process.env.NODE_ENV == 'production' ? 'dist' : 'client';

app.use(express.static(__dirname + '/' + rootFolder));

// give access to vid and thumb files generated by python
app.use('/python', express.static(__dirname + '/python'));

// log every request to the console
app.use(logger('dev'));
app.use(bodyParser.json());

// get an instance of router
var router = express.Router();
app.use('/', router);

// API Routes
//router.get('/api/btstart', api.btstart);
//router.get('/api/btstop', api.btstop);
//router.get('/api/processing', api.processing);

// expose app
exports = module.exports = app;

app.set('port', process.env.PORT || 3000);
server.listen(app.get('port'));

//console.log('Listening: ' + app.get('port'));